apiVersion: v1
kind: Pod
metadata:
  name: mysecretpod
spec:
  containers:
  - name: mypod
    image: nginx
    env: 
      - name: MYSECRET
        valueFrom:
          secretKeyRef:
             name: secret-basic-auth
             key: username
      
