apiVersion: v1
kind: Pod
metadata:
  name: mysecretpod
spec:
  containers:
  - name: mypod
    image: nginx
    volumeMounts:
    - name: secretmount
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: secretmount
    secret:
      secretName: secret-basic-auth